### ISSUE TITLE
RPC call failed

### ISSUE THREAD

**Issue by AllieQpzm** [allquixotic/encuum#1]
Hey,

When trying to run it works up until a certain point before getting this message a few times and stopping.

```
RPC call failed: ErrorObject { code: ServerError(-32099), message: "The result is empty.", data: None }
RPC call failed: ErrorObject { code: ServerError(-32099), message: "The result is empty.", data: None }
RPC call failed: ErrorObject { code: ServerError(-32099), message: "The result is empty.", data: None }
RPC call failed: ErrorObject { code: ServerError(-32099), message: "The result is empty.", data: None }
RPC call failed: ErrorObject { code: ServerError(-32099), message: "The result is empty.", data: None }
RPC call failed: ErrorObject { code: ServerError(-32099), message: "The result is empty.", data: None }
Error: RPC call failed: ErrorObject { code: ServerError(-32099), message: "The result is empty.", data: None }

Caused by:
    RPC call failed: ErrorObject { code: ServerError(-32099), message: "The result is empty.", data: None }
```

Let me know if you need any more info.

Thanks!

**Comment by allquixotic** [comment]
Hmm... this looks like the Enjin server decided to stop responding to you.

About how long does the program run before this happens? I have the code designed to try several times and wait 1 minute between retries when the server gives us an error or times out. On my system, I occasionally get different errors, like error 502 (Bad Gateway), which the program can get past simply by waiting 1-2 minutes.

And what is the immediate log line that displays in the console before the RPC call failures start happening?

**Comment by allquixotic** [comment]
I get the error that the "module doesn't exist" when trying to visit the link you provided, but I'm also not a member of that Enjin website.

A forum post that comes back with an empty response is anomalous indeed. I didn't encounter that on my site with nearly 20,000 posts over more than 5,000 threads.

If you want, I can add an option `keep_going` to skip past server errors and continue on anyway. This would have the downside of skipping over any bugs in Encuum that might be something we can fix, but it would still log the error message and continue.

**Comment by allquixotic** [comment]
Can you retest with the current master version of encuum (do a `git pull` or re-download the .zip file)? Thanks!

**Comment by Zamotic** [comment]
Got pretty far into the scrape before I started getting the same error as above:
```[src\forum.rs:241] f = "Thread: 8734775, Try #2: RPC call failed: ErrorObject { code: ServerError(-32099), message: \"The result is empty.\", data: None }"
[src\forum.rs:241] f = "Thread: 8734775, Try #3: RPC call failed: ErrorObject { code: ServerError(-32099), message: \"The result is empty.\", data: None }"
[src\forum.rs:241] f = "Thread: 8734775, Try #4: RPC call failed: ErrorObject { code: ServerError(-32099), message: \"The result is empty.\", data: None }"
thread 'main' panicked at 'Thread: 8734775, Try #5: RPC call failed: ErrorObject { code: ServerError(-32099), message: "The result is empty.", data: None }', src\forum.rs:238:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace```
I wonder if this is an anti-DDOS "feature" where if the API receives a certain number of calls in a certain time it starts ignoring calls?

**Comment by allquixotic** [comment]
I don't think this is an anti-DDOS feature. You might be getting an empty call if you don't have access to view the thread; that's just a guess though.

You can set `keep_going=true` in the `.env` file to ignore these, or if you want, I can make it the default behavior to ignore empty response bodies or empty results

**Comment by allquixotic** [comment]
I've added error handling to `Forum.getThread` and `Forum.getPost` (the two API calls that are called a lot) to automatically fail, log the error, and keep going if the error message contains any of the following:

 - The result is empty
 - thread has been moved
 - noaccess

This should prevent the known errors that prevent you from accessing a thread which I believe are **not bugs in Encuum**. These errors suggest a permissions problem (noaccess), a thread move ("thread has been moved" - you will be able to download it from the place where it was moved to), or a thread that is no longer accessible for an unknown reason ("The result is empty").

The improved code will prevent the downloader from being slowed down a lot by trying repeatedly (and waiting between each try) when it encounters any of these conditions.

I suggest you pipe the content of the Encuum log to disk: 

 - [Windows instructions for piping the log to disk](https://stackoverflow.com/questions/1420965/how-to-redirect-windows-cmd-stdout-and-stderr-to-a-single-file)
 - [Mac/Linux instructions](https://stackoverflow.com/questions/876239/how-to-redirect-and-append-both-standard-output-and-standard-error-to-a-file-wit)

--------

I believe your issue to be solved. **Please help me by retesting and providing your feedback here.**

**If you cloned using Git:** Remove the file `Cargo.lock` in the encuum directory, then `git pull`.

**If you downloaded the Zip file:** Just download another version of the zip from the same link as in the readme. Discard your previous copy of encuum and try again.

**Comment by allquixotic** [comment]
Closing as fixed due to lack of updates. Please reopen if this happens again.
