### ISSUE TITLE
I want to add some of the missing features

### ISSUE THREAD

**Issue by Kneesnap** [allquixotic/encuum#13]
Hello,

I'm looking to export my website data. Given the time-sensitivity of the matter, I'm a little worried. I need these features:
 Saving users
 Saving wikis
 Saving staff applications (Templates + Individual applications)
 Saving News posts (via the Enjin News module)
 Saving Minecraft-specific stuff (I'm not sure entirely what this refers to, could I get clarification? I probably need this)
 Saving Shop-specific stuff (unlikely to be done by @allquixotic)

I'd like clarification on all of the previously mentioned features (as well as other features which you list in the readme).
 * What data can be saved, and what data cannot be saved.

Which features would you prefer I work on?
Do you have a discord? I'd like to move this discussion there because it's not well suited for a github issue. If you want to add me, I'm Kneesnap#7540

I don't have a lot of free time to dedicate, so I probably can't implement all of these, but I can implement
What I'm willing to implement right now:
 - Saving users (Let me know what kind of data you want saved...)

**Comment by allquixotic** [comment]
See [CONTRIBUTING.md](https://github.com/allquixotic/encuum/blob/master/CONTRIBUTING.md) for some basic primer on stuff you can contribute.

**Comment by allquixotic** [comment]
I sent you a friend request on Discord with my tag ending in #0709.

**Comment by allquixotic** [comment]
The encuum project is now unmaintained. Another developer has managed to write a much more complete Enjin extractor over here: https://github.com/Kas-tle/EnjinScraper Please use that going forward.
