### ISSUE TITLE
Logging Stops Early

### ISSUE THREAD

**Issue by TamBarlas** [allquixotic/encuum#20]
Seems the logging function is stopping before the program completes.  In the attached INFO-level log file you can see the text "LOGGING STOPPED HERE", below which I copied-and-pasted from my terminal window.

[log_file info test.txt](https://github.com/allquixotic/encuum/files/11160743/log_file.info.test.txt)

**Comment by allquixotic** [comment]
Hi, that's a little strange. It might be a buffering issue in the logging infrastructure. I haven't seen this on my computer, but maybe it's a Windows thing - I'm running on MacOS...

**Comment by allquixotic** [comment]
The encuum project is now unmaintained. Another developer has managed to write a much more complete Enjin extractor over here: https://github.com/Kas-tle/EnjinScraper Please use that going forward.
