### ISSUE TITLE
Seems like it falters maybe with the images

### ISSUE THREAD

**Issue by itivae** [allquixotic/encuum#22]
Hi ,

First thanks a bunch for writing this. I have run this now three times here is a copy of my .dev file and what seem to be happening It just stops. Any help appreciated
.dev:
email=********
password=********
website=www.ein-gaming.com
database_file=ein-gaming-3.db
forum_ids=144953
do_images=true
keep_going=true
log_level=TRACE
log_file=einsite.log
sanitize_log=true

Log file is here. Its pretty big so i put it in drive. Any help is appreciated. Thanks
(link redacted)

**Comment by allquixotic** [comment]
I'm really not sure what's going on here. You should delete that post on Drive ASAP, please. It's for your own data protection.

Question: Is your output database missing anything that you expect it to have, in terms of forums or applications?

**Comment by allquixotic** [comment]
The encuum project is now unmaintained. Another developer has managed to write a much more complete Enjin extractor over here: https://github.com/Kas-tle/EnjinScraper Please use that going forward.
