### ISSUE TITLE
Scrape Wikis In Scraper

### ISSUE THREAD

**Issue by Kas-tle** [allquixotic/encuum#25]
I would have commented on the other issue but you locked it to collaborators so I could not...

It is fairly easy to implement this and not get access errors. You just need to obtain and use a specific cf_bm cookie for all your requests. I implemented this in my own scraper and don't run into any rate limiting issues if you'd like an example:

https://github.com/Kas-tle/EnjinScraper/blob/main/src/scrapers/wiki.ts#L216-L220

Also to get comments enjin has an undocumented comments API which works for wiki, applications, and news posts.

**Comment by allquixotic** [comment]
Actually, I don't really have much time to make encuum any better than it is, and given that your project seems to do all that mine can do and much more, I think I'm going to hang up the hat and call encuum done. I'll edit the readme to show that it's unmaintained and provide a link to your project. You've got way more stuff over there that seems to be working, and given that we have about 2 weeks until Enjin shuts down, there's no sense in me improving this project. I've got better things to do.

Thanks for your hard work on EnjinScraper!
