### ISSUE TITLE
subforum_ids doesn't seem to work

### ISSUE THREAD

**Issue by AvrikV** [allquixotic/encuum#3]
Hi, thanks for adding my suggestion in the other version. For some reason I can't get it to work though. It detects the website and forum but then stops abruptly at this point with no errors.

```
PS J:\encuum> cargo run --release
    Finished release [optimized] target(s) in 5.13s
     Running `target\release\encuum.exe`
got a site forum instance (aka prefix or caf) 33755660 called (Website forum name)
```

I ran it without the subforum command and it ran just fine afterward so maybe something is wrong with the subforum_ids option.

**Comment by allquixotic** [comment]
Thanks for the report! I'm working on a partial rewrite of this tool that should improve this bug.

**Comment by allquixotic** [comment]
Can you retest with the current master version of encuum (do a `git pull` or re-download the .zip file)? Thanks!

**Comment by allquixotic** [comment]
OK, so I finally figured out what the heck was going on with Encuum not finding certain forums. Turns out I was reading the data entirely wrong in the `Forums.getCategoriesAndForums` call. I've now (at 01:13 AM EST, 01/29/23) committed code that seems to _really_ find all the forums, subforums, sub-sub-forums, sub-sub-sub-forums, etc. It seems to be able to really find them all.

Still debugging other issues, but I _think_ this one is finally fixed. Please retest and let me know. Thanks!

**Comment by AvrikV** [comment]
Tried it out but I'm getting an error while compiling.

```
error[E0432]: unresolved import `tokio::signal::unix`
  --> C:\Users\----\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-cron-scheduler-0.9.3\src\job_schedu
ler.rs:16:20
   |
16 | use tokio::signal::unix::SignalKind;
   |                    ^^^^ could not find `unix` in `signal`

error[E0433]: failed to resolve: could not find `unix` in `signal`
   --> C:\Users\----\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-cron-scheduler-0.9.3\src\job_sched
uler.rs:384:46
    |
384 |             if let Some(_k) = tokio::signal::unix::signal(signal)
    |                                              ^^^^ could not find `unix` in `signal`

   Compiling migration v0.1.0 (J:\encuum\migration)
Some errors have detailed explanations: E0432, E0433.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `tokio-cron-scheduler` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
```

Googled around for this error and it sounds like it might not be compatible with Windows?

**Comment by allquixotic** [comment]
Oops, thanks for reporting that! I've been playing around with some changes and it seems like tokio-cron-scheduler doesn't support Windows with a feature I was using.

The compiler error on Windows should be fixed now. Can you please retest?

**Comment by AvrikV** [comment]
Works well now. Got the entire subforum saved. Thanks!

**Comment by allquixotic** [comment]
I'm glad!
