### ISSUE TITLE
error [E0432] and [E0433]

### ISSUE THREAD

**Issue by FuzzyThor** [allquixotic/encuum#6]
PS O:\encuum-master> cargo run --release
   Compiling tokio-cron-scheduler v0.9.3
error[E0432]: unresolved import `tokio::signal::unix`
  --> C:\Users\Skate\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-cron-scheduler-0.9.3\src\job_scheduler.rs:16:20
   |
16 | use tokio::signal::unix::SignalKind;
   |                    ^^^^ could not find `unix` in `signal`

error[E0433]: failed to resolve: could not find `unix` in `signal`
   --> C:\Users\Skate\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-cron-scheduler-0.9.3\src\job_scheduler.rs:384:46
    |
384 |             if let Some(_k) = tokio::signal::unix::signal(signal)
    |                                              ^^^^ could not find `unix` in `signal`

Some errors have detailed explanations: E0432, E0433.
For more information about an error, try `rustc --explain E0432`.

**Comment by allquixotic** [comment]
Hi, this should be fixed now. Looks like this might be from an earlier version of the code. I believe I've removed the offending dependency.

**If you cloned using Git:** Remove the file `Cargo.lock` in the encuum directory, then `git pull`.

**If you downloaded the Zip file:** Just download another version of the zip from the same link as in the readme. Discard your previous copy of encuum and try again.

**Comment by FuzzyThor** [comment]
I downloaded the updated release and it was able to pass this.
