### ISSUE TITLE
Extractor appears not to be grabbing Sticky Threads

### ISSUE THREAD

**Issue by Linnuial** [allquixotic/encuum#9]
I used encuum on my enjin site and double-checked the forum_posts table (using DbVisualizer) and found a discrepancy between the number of rows vs. Enjin's reported number of threads.

It seems that none of the Sticky Threads got extracted.

**Comment by allquixotic** [comment]
Thanks for the bug report! I think this one might be valid, so I'll double check on my side and see if I can reproduce the problem. I'll let you know once I test it this weekend. Stay tuned!

**Comment by allquixotic** [comment]
I believe your issue to be solved. **Please help me by retesting and providing your feedback here.**

**If you cloned using Git:** Remove the file `Cargo.lock` in the encuum directory, then `git pull`.

**If you downloaded the Zip file:** Just download another version of the zip from the same link as in the readme. Discard your previous copy of encuum and try again.

**Comment by Linnuial** [comment]
Hi there. I tried to test tonight but now the app gives me: 

PS C:\Users\ecvor\Desktop\encuum_v2\encuum-master> cargo run --release
    Finished release [optimized] target(s) in 0.57s
     Running `target\release\encuum.exe`
thread 'main' panicked at 'State not initialized', src\main.rs:70:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\release\encuum.exe` (exit code: 101)

I put this version of encuum in its own folder and copied my .env file from the previous version into this one. Though I'm not sure it's even getting to the point where it's reading from that file. 

I am a total RUST newb so not sure if I missed some prereq step.

**Comment by allquixotic** [comment]
Hi,

That was another bug that I didn't catch last time around. :( I have fixed it now. Thank you for finding it!

**Comment by Linnuial** [comment]
I apologize for taking so long to get back to retesting.

I ran the program for a while, but it eventually seemed to hang with this error:

2023-03-08T05:11:41.188420Z  INFO encuum::applications: Saved application 2757820
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Parse error: invalid type: integer `0`, expected a string at line 1 column 60

Caused by:
    invalid type: integer `0`, expected a string at line 1 column 60', src\main.rs:195:38
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2023-03-08T05:11:41.358280Z ERROR tokio_cron_scheduler::job::creator: Error running job 45aa1c09-87f2-489a-974f-9d673267596b RecvError(())

I'll attach the full log file, though it does not include the above error (stops just before it). 
[elentiri3.log](https://github.com/allquixotic/encuum/files/10917445/elentiri3.log)

The good news is that the Sticky Thread issue seems to be resolved. And from what I can tell by spot-checks, everything else seems to be there also.
